### ISSUE TITLE
Use custom items / named items for tool

### ISSUE THREAD

**Issue by Tabletopcheese** [Wolfst0rm/ArmorStandEditor-Issues#13]
### Is your feature request related to a problem?

Allow names or custom items to be used as tool, or items with custom model data.

### Describe the solution you'd like.

Be able to use a named item, that is normally unobtainable for players to trade and buy with diamonds.

### Describe alternatives you've considered.

 I asked in paper discord if its possible. 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

![image](https://user-images.githubusercontent.com/14104281/141259246-bbdc26a4-f855-44c4-978c-72ac82bc27bb.png)

![image](https://user-images.githubusercontent.com/14104281/141259275-8d2a6c34-eb55-4fc7-ad6f-52c7b3554b94.png)

im also on discord for clarifications TabletopCheese#0846

**Comment by Tabletopcheese** [comment]
Is this not being considered anymore?

Just curious cause if it turned out to be more difficult than it sounded, I know of an open source plugin that pretty much makes a unique item for gold nuggets, and has the option to just use normal gold nuggets.

And it is just an on and off option in the config, I cant find our original conversation about this. But let me know here I guess!

**Comment by Wolfieheart** [comment]
If you could provide an example of this, I will reconsider it for implementation into v1.18.1-33 as the finalization of the next version is almost complete :)

**Comment by Tabletopcheese** [comment]
Yes yes!

So they make the item just have like a custom model ID, give it a name, and
have a command to generate it.

https://github.com/DarkBlade12/ItemSlotMachine

This plugin is where I've seen its, and is open source.


Just reiterating, they use gold nugget and have the option for it to be a
normal nugget or the custom one.

This way any flint won't work.

**Comment by Wolfieheart** [comment]
Since we already support lore, I don't think it is useful (at the current stage) to add CustomNames into the mix, since you can already generate FLINT and turn requireItemLore to true and with the format you need for the lore. 

Moving this to closed. Sorry, but thank you for helping and allowing me to consider this :)

**Comment by Tabletopcheese** [comment]
No worries at all! Not all ideas fit scope.
