### ISSUE TITLE
Option to require sneak to use editor.

### ISSUE THREAD

**Issue by mibby** [Wolfst0rm/ArmorStandEditor-Issues#17]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like.

An option to require sneaking when interacting with flint to open and use the armorstand editor, to prevent any possible conflicts with normal flint use.

### Describe alternatives you've considered.

An old fork of ArmorStandEditor had this feature, but I don't remember which it came from.

```
#If true, the GUI will only open if the player is sneaking
requireSneaking: true
```

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Wolfieheart** [comment]
Had a look through all of the other forks in an attempt to find this. Might have been in an older version of the plugin as well. 
But for now I dont see the need to enable this since its sneaking enabled to activate most things IIRC.

Will check this again in the new year for progress. If you find the fork in the mean time let me know and I will investigate further.

**Comment by mibby** [comment]
I believe it came from this fork.
https://github.com/jDanek/ArmorStandEditor/commit/464fbd4cc9070bb6b7ff95df316d85a029b0e745

**Comment by Wolfieheart** [comment]
Oh thanks for finding it. Will investigate and see if worth while adding
shortly!

Kr,

>

**Comment by Wolfieheart** [comment]
Accepted since Minor Changes are required for this to work.

**Comment by Wolfieheart** [comment]
Ok I have a test version for you to test this on :)

https://github.com/Wolfst0rm/ArmorStandEditor/suites/4638820317/artifacts/125713507

Extract that and add it to your server, and see what is working and what isn't :) Lemme know if something doesn't work as intended.
