### ISSUE TITLE
[Internal] Tidy up debug messages

### ISSUE THREAD

**Issue by Wolfieheart** [Wolfst0rm/ArmorStandEditor-Issues#19]
### Is your feature request related to a problem?

No

### Describe the solution you'd like.

Debug output via Print Function is tidied up. At the moment it is currently set to:

``` 	
       /*
	*	For Internal Debugging -
	*
	*   set debug: true in Config.yml
	*   NOTE: NOT RECOMMENDED FOR PROD! INTERNAL TESTING ONLY!
	*
	* 	To be refactored - Per person messages MAYBE!
	*/
	public void print(String message){
		if(debug){
			this.getServer().broadcastMessage(message);
			log(message);
		}
	}
``` 

it would be nice for one that we could drop the broadcasting to the server. Especially if we are dealing with players here. Would be nicer if this is not done.

For two that the debug log via the print method is logged as is now via console, but also into an ASE.log file. Means easier bug reports so with Debug we can see what goes wrong and where.

### Describe alternatives you've considered.

n/a

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

More a nice beginner issue if people want to fork this project to do so. But I can also do it as required.

**Comment by Sikatsu** [comment]
@Wolfst0rm Not sure if you knew, but on the latest version you released everyone sees this:
![image](https://user-images.githubusercontent.com/5664135/146645302-cc1d491c-0f82-4726-a18a-ff045042d359.png)

Can this not be made as a global announcement?

**Comment by Wolfieheart** [comment]
Yeah noted, check my profile on the SpigotMC WEbsite :)

**Comment by Wolfieheart** [comment]
Hotfix published. Version Number not adjusted for this.
