### ISSUE TITLE
Lock and Unlock of ArmorStand and ItemFrames being handled incorrectly

### ISSUE THREAD

**Issue by ABKTiltControls** [Wolfst0rm/ArmorStandEditor-Issues#2]
### Expected behavior

When looking at an armor stand and I press F, I expect the armor stand to target lock and see message "ArmorStand target locked" -- and a similar message when unlocking the armor stand. I also expect the message "ItemFrame target locked" when locking an item frame -- and similar message when unlocking.

### Observed/Actual behavior

When locking or unlocking an armor stand, I saw "Itemframe target unlocked"
When locking an item frame, I saw "ArmorStand target locked"
When unlocking an item frame, I saw "ArmorStand target unlocked"
![image](https://user-images.githubusercontent.com/53723250/129966700-654cdf31-1c46-486f-ae6a-448201093e63.png)
![image](https://user-images.githubusercontent.com/53723250/129966753-4055b444-e927-43b8-82ba-4f53fe4f86c3.png)
![image](https://user-images.githubusercontent.com/53723250/129966797-ce275a7f-7989-4ec4-80b2-48aa597785f6.png)
![image](https://user-images.githubusercontent.com/53723250/129966837-9173356a-bc41-40fd-9085-39e763ec9c77.png)

### Steps/models to reproduce

Place item frame or armor stand
Hold editor tool in hand
Press F on or off target

### Plugin list

Plugins (10): ArmorStandEditor, CoreProtect, FarmControl, LuckPerms, Multiverse-Core, Multiverse-Portals, SafeSpectate*, TabTPS, WorldEdit, WorldGuard

### Other

I double checked the values in en_US.yml file and they were the expected values as pasted below:
`target:
  msg: ArmorStand target locked.
notarget:
  msg: ArmorStand target unlocked.
frametarget:
  msg: Itemframe target locked
noframetarget:
  msg: Itemframe target unlocked.`

**Comment by Wolfieheart** [comment]
First Conclusion: it could be something in PlayerEditor L442: 
https://github.com/Wolfst0rm/ArmorStandEditor/blob/af939d61d3b16a10fae741aa1ca938ec46ed9e2b/src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditor.java#L442

To be tested further later today. 

Thanks for reporting this and using the template :)

**Comment by Wolfieheart** [comment]
Reproduced on 1.16.5 with the DEV Version - Investigating further as to why its falling into the first loop in place of the loop for ItemFrames

**Comment by Wolfieheart** [comment]
Feel free to test with this artifact and see if it reoccurs :) - https://github.com/Wolfst0rm/ArmorStandEditor/actions/runs/1148375879 

I confirmed testing with the latest paper on 1.17 and everything works fine for me :) I will Close once you confirm its good, otherwise will be autoclosed in a weeks time

**Comment by Wolfieheart** [comment]
Thanks for reporting this btw :) 

Closing and releasing this version!
