### ISSUE TITLE
[Bug]: Armorstand Editor 1.18.1-32

### ISSUE THREAD

**Issue by Blockdigga** [Wolfst0rm/ArmorStandEditor-Issues#22]
### Expected behavior

Armorstand  Frame  glow  by select ( with Firestone) and move  the Armorstand.

![2021-12-30_16 24 39](https://user-images.githubusercontent.com/96879509/147767444-4501b1dc-a5fc-4d5d-a538-893003dc9933.png)

### Observed/Actual behavior

it dosnt Glow

![Armorstand Editor 1 18](https://user-images.githubusercontent.com/96879509/147767158-0ccd8f97-0606-40a3-b814-9a25a5566573.jpg)

### Steps/models to reproduce

Select with Firestone the Armorstand in Version 1.18.1-32 ( no Glow)

Select with Firestone the Armorstand in Version 1.16 -25 ( Glow) 

### Plugin list

---

### Plugin Version

Armorstand Editor 1.18.1-32

### Server Version

Paper MC 1.18.1 101

**Comment by Wolfieheart** [comment]
This most likely is probably due to the change with the Disabling of Slots and how Teams work. Checking on my end to see whats up :)

**Comment by Wolfieheart** [comment]
Unable to reproduce with the latest development build (or what will become 1.18.1-33)
