### ISSUE TITLE
[Bug]: Cannot punch armor stands when they are invisible on 1.18.2-35

### ISSUE THREAD

**Issue by sxphirus** [Wolfst0rm/ArmorStandEditor-Issues#28]
### Expected behavior

Hitting an invisible armor stand while holding flint would move it in the other direction to what right clicking it does

### Observed/Actual behavior

Armor stand does not move, instead it opens the editor

### Steps/models to reproduce

Punch an invisible armor stand with the flint while in an editor mode.

### Plugin list

Plugins (58): ajQueue, AreaShop, ArmorStandEditor, ArtMap, BBeeChecker, ChangeSlots, ChatControlRed, CommandPanels, CommandWhitelist, CoreProtect, emoteGen, EntityDetection, EpicRename, Essentials, GSit, HeadDatabase, HMCCosmetics, HolographicDisplays, HuskHomes, HuskHomesGUI, ImageMaps, KixsAutoAnnouncerPremium, Lasso, LiteBans, LuckPerms, Minepacks, MyCommand, Nightvision, OpenInv, OtherAnimalTeleport, PacketLimiter, PlaceholderAPI, Plan, PluginManager, PremiumVanish, PriceFloor, ProtocolLib, Redye, SaphirusFormat, Shopkeepers, ShopKeepersMeta, Shopworld, ShowItem, SilenceMobs*, SkinsRestorer, SkullGiver, SpectatorMode, SyncInv, TAB-Bridge, UltimateAutoRestart, UnifiedMetrics, Vault, VoidGen, Vulcan, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldSpawn*

### Plugin Version

1.18.2-35

### Server Version

1.18.2 Paper Build 260

### Other

This was not an issue on the release version.

**Comment by Wolfieheart** [comment]
Will investigate later today, strange thing is nothing has changed in the logic when hitting an invisible armor stand. 

(if you can) a full reproduction video of this would be nice so I can test and have a look, later on :)

**Comment by sxphirus** [comment]
https://cdn.discordapp.com/attachments/732236633537118340/955386426793533461/2022-03-21_08-43-11.mp4
```
[08:46:33 INFO]: Plugins (5): ArmorStandEditor, Essentials, LuckPerms, ProtocolLib, Vault
[08:46:39 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b550
[08:46:39 INFO]: Provides read/write access to the Minecraft protocol.
[08:46:39 INFO]: Authors: dmulloy2 and comphenix
```

**Comment by sxphirus** [comment]
https://cdn.discordapp.com/attachments/732236633537118340/955388514814529576/2022-03-21_08-52-27.mp4
downgrading to latest release ^

**Comment by Wolfieheart** [comment]
Noticed my mistake (i think). New build with a potential fix should be available [here](https://github.com/Wolfieheart/ArmorStandEditor/actions/runs/2015091808) shortly.

NOTE: You need to download the Artifact Zip, Extract it and add the plugin to the Plugins Folder. I will have to test this myself later, I cant at the moment as I am at work.

**Comment by sxphirus** [comment]
issue still persists on the latest build
thank you for your quick response btw!

**Comment by Wolfieheart** [comment]
Ok then it was not what I thought it was. Will attempt to reproduce later today.

And anytime! Thank you for testing the next version of ASE :D

**Comment by Wolfieheart** [comment]
OK It was apparently an issue with how event priorities are handled in game. Reverted it back to what it was in 1.18.2-34.1 and reimplemented the protection changes. Should work but please test this yourself, then I can close this :)

That was actually hard to find, but a challenge, which is what I like 👍 
https://github.com/Wolfieheart/ArmorStandEditor/actions/runs/2017486484

**Comment by sxphirus** [comment]
Thank you!
