### ISSUE TITLE
Itemframe invisible rotate issue 

### ISSUE THREAD

**Issue by Sikatsu** [Wolfst0rm/ArmorStandEditor-Issues#3]
### Expected behavior

That the item doesn't rotate and that the flint doesn't go in the itemframe.

### Observed/Actual behavior

When making the itemframe invisible, and the itemframe already contains an item; using right click to make the itemframe invisible, it will rotate. (With left click it will not rotate). If the itemframe does not contain an item, the flint item will go into it.

### Plugin Version

1.17.1-29.1

### Server Version

This server is running Purpur version git-Purpur-1351 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8fc7931 on ver/1.17.1)
You are 3 version(s) behind
Previous version: git-Purpur-1341 (MC: 1.17.1)

**Comment by Sikatsu** [comment]
A video that displays the issue:

https://cdn.discordapp.com/attachments/184716181263876096/881901316488704071/Minecraft__1.17.1_-_Multiplayer_3rd-party_Server_2021-08-30_16-00-15.mp4

**Comment by Wolfieheart** [comment]
Will investigate this once #5  is closed :D

**Comment by Wolfieheart** [comment]
Ok switching focus to this now that #5 is closed. 

> That the item doesn't rotate

I had intended to add this at some stage soon as it appears to not be implemented. It is an extension of #1 in a way: https://github.com/Wolfst0rm/ArmorStandEditor-Issues/issues/1#issuecomment-886070504

>  that the flint doesn't go in the itemframe.

If I can get it to stop rotating, I will probably also prevent the editTool from going in as well. 

Going to mark this as a new feature rather than a bug IMO, as it is something that hasn't been implemented yet.

**Comment by Sikatsu** [comment]
Yeah, I think if you are using the itemframe visibility setting that a right click should not rotate the item, just like a left click doesn't.

And gotcha! Thanks, it'd be a nice improvement.

Do you think it would be possible to other than making itemframes invisible, also make them fixed / invulnerable?

**Comment by Wolfieheart** [comment]
> Do you think it would be possible to other than making itemframes invisible, also make them fixed / invulnerable?

Well we have a way to get the itemFrame that is currently being looked at, so it could be. I will check it out tomorrow to be sure before starting with any implementation :)

**Comment by Sikatsu** [comment]
No rush! Thanks for your work. Do you by any chance accept donations?

**Comment by Wolfieheart** [comment]
I do not -> I dont like accepting donations for stuff that was originally free. Thanks for offering though :)

**Comment by Sikatsu** [comment]
Understood! Just wanted to justify for the time spend. ^^
Also found a small issue I think, listed in #5

**Comment by Wolfieheart** [comment]
Rrrrrr don't know why this closed. Will reopen it as it has not been
implemented.

**Comment by Wolfieheart** [comment]
Dev has been started for this. You can view it here; https://github.com/Wolfst0rm/ArmorStandEditor/tree/dev/frameRotateWhenInvisibleCheck

**Comment by Sikatsu** [comment]
Awesome!

**Comment by Wolfieheart** [comment]
Hrmm looking into this, and wondering if the implementation that I have in, looks good. 

Only run IF the itemFrame is Invis cause I can see this being a problem if the itemFrame is Visible. We shouldn't run the eventHandler if the ItemFrame is Visible.

If Invis, then get the nearest ItemFrames to the player, and loop over them.
If it contains Flint - Cancel the event. 

I assume that ```event.setCancelled(true);``` will also stop the rotation event, I could be wrong but I think it meets the requirements for this. 

Full Code of what has been Implemented:

```	@EventHandler(priority = EventPriority.LOW, ignoreCancelled = true)
	void checkItemFrameRotate(PlayerInteractEntityEvent event){
		Player player = event.getPlayer();
		if(event.getRightClicked() instanceof ItemFrame){
			boolean itemFrameInvis = ((ItemFrame) event.getRightClicked()).isVisible();
			if(itemFrameInvis) {
				itemFrameRotated = getFrameTargets(player);
				if (!itemFrameRotated.isEmpty()) {
					for (int i = 0; i < itemFrameRotated.size(); i++) {
						if (itemFrameRotated.get(i).getItem().getType() == Material.FLINT) {
							event.setCancelled(true);
						}
					}
				}
			}
		}
	}```

**Comment by Wolfieheart** [comment]
Wait thats only for it has Flint as an Item already inside it. yeh not correct. Need to fix that

**Comment by Wolfieheart** [comment]
Gonna break it down more and do more work on this. keep an eye on the repository and PRs

**Comment by Wolfieheart** [comment]
Take a look at that commit and let me know if it is what you were thinking :)

**Comment by Wolfieheart** [comment]
Ok I am so sorry about this I keep looking at this and going.... NOPE that's not correct and I keep wrecking my head with this. Commiting it now after breaking it down like crazy

**Comment by Wolfieheart** [comment]
Going to start the PR on this so I can give you TestBuilds :)

**Comment by Wolfieheart** [comment]
Build can be found on: https://github.com/Wolfst0rm/ArmorStandEditor/suites/3702611345/artifacts/90368851

Report the issues to Wolfst0rm/ArmorStandEditor#6

**Comment by Wolfieheart** [comment]
Added notes to #11 related to this. Explaining that I wanted to fix it but currently its not possible.  Will leave this open as I am hoping that if someone else were to come along and have a look and see this that someone could fix it as well.
