### ISSUE TITLE
Can't translate on/off keys

### ISSUE THREAD

**Issue by Sikatsu** [Wolfst0rm/ArmorStandEditor-Issues#6]
### Expected behavior

Being able to translate the on/off keys for gravity.

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/5664135/131393864-8448cbcb-48d8-4d62-a532-9fef4ed180e1.png)
![image](https://user-images.githubusercontent.com/5664135/131393883-3bef3c01-6214-4fd7-896d-5d1ed391ddd0.png)

![image](https://user-images.githubusercontent.com/5664135/131393971-af32178f-d6ba-47a9-a1a6-44362b6fdcd2.png)

**Comment by Wolfieheart** [comment]
Initial Investigation is that it is related to: https://github.com/Wolfst0rm/ArmorStandEditor/blob/master/src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditor.java#L350

Actually I am 100% sure on that, but going to have to debug it a bit which wont happen til this weekend probably.

**Comment by Sikatsu** [comment]
Yeah that seems to be the reason why!

**Comment by Wolfieheart** [comment]
Will be commiting a review of this soon. Might have made it easier and changed the on/off keys to simple True/False but have the messages be on and off. Was the easiest way to fix this.

**Comment by Sikatsu** [comment]
Awesome, thank you! If theres a build out regarding this or the item frames i'll test it out. 😄

**Comment by Wolfieheart** [comment]
There should already be a test build available. You can find it on: https://github.com/Wolfst0rm/ArmorStandEditor/suites/3683823741/artifacts/89742223

**Comment by Sikatsu** [comment]
This is now solved and can be closed, thank you! ^^

**Comment by Wolfieheart** [comment]
Fixed as of: https://github.com/Wolfst0rm/ArmorStandEditor/commit/8f4e99886a36442f66594f196eba4340629336f5
