### ISSUE TITLE
Ability to Toggle itemFrame Fixed Status

### ISSUE THREAD

**Issue by Wolfieheart** [Wolfst0rm/ArmorStandEditor-Issues#9]
### Is your feature request related to a problem?

We want the ability to be able to toggle the ItemFrame.isFixed setting on the fly.

### Describe the solution you'd like.

The ability to toggle the ItemFrame Fixed Flag

### Describe alternatives you've considered.

N/A

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

### Other

Planned for v1.17.1-31, next Priority after Merging in Wolfst0rm/ArmorStandEditor#6

**Comment by Wolfst0rm** [comment]
Priority for v1.17.1-31:

- Code Review Remarks from CodeFactor
- Implementation of #9
- Implementation of #8 (if possible, testing with a smaller project atm)
